-- MySQL Script generated by MySQL Workbench
-- 06/08/16 20:32:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema guara_tattoo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `guara_tattoo` ;

-- -----------------------------------------------------
-- Schema guara_tattoo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `guara_tattoo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `guara_tattoo` ;

-- -----------------------------------------------------
-- Table `guara_tattoo`.`loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`loja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(100) NULL,
  `nome_fantasia` VARCHAR(100) NULL,
  `CNPJ` VARCHAR(20) NULL,
  `CEP` VARCHAR(20) NULL,
  `cidade` VARCHAR(100) NULL,
  `bairro` VARCHAR(100) NULL,
  `numero` INT(5) NULL,
  `logradouro` VARCHAR(100) NULL,
  `UF` VARCHAR(45) NULL,
  `responsavel` VARCHAR(100) NULL,
  `telefone` VARCHAR(20) NULL,
  `celular` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `telefone` VARCHAR(15) NULL,
  `celular` VARCHAR(15) NULL,
  `email` VARCHAR(100) NULL,
  `CPF` VARCHAR(20) NULL,
  `RG` VARCHAR(20) NULL,
  `dataNasc` VARCHAR(20) NULL,
  `CEP` VARCHAR(20) NULL,
  `cidade` VARCHAR(100) NULL,
  `bairro` VARCHAR(100) NULL,
  `logradouro` VARCHAR(100) NULL,
  `numero` INT(5) NULL,
  `UF` VARCHAR(10) NULL,
  `referencia` VARCHAR(300) NULL,
  `obs` VARCHAR(3000) NULL,
  `dataCadastro` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`anamneses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`anamneses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`clientes_anamneses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`clientes_anamneses` (
  `clientes_id` INT NOT NULL,
  `anamneses_id` INT NOT NULL,
  PRIMARY KEY (`clientes_id`, `anamneses_id`),
  INDEX `fk_clientes_anamneses_anamneses1_idx` (`anamneses_id` ASC),
  CONSTRAINT `fk_clientes_anamneses_clientes`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `guara_tattoo`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_anamneses_anamneses1`
    FOREIGN KEY (`anamneses_id`)
    REFERENCES `guara_tattoo`.`anamneses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`tipos_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`tipos_servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  `ativo` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`profissionais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`profissionais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `telefone` VARCHAR(20) NULL,
  `CPF` VARCHAR(20) NULL,
  `data_entrada` VARCHAR(10) NULL,
  `salario` DECIMAL(10,2) NULL,
  `comissao` DOUBLE(10,2) NULL,
  `ativo` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `senha` VARCHAR(30) NULL,
  `cadastro_clientes` TINYINT(1) NULL,
  `cadastro_profissionais` TINYINT(1) NULL,
  `lancamento_servicos` TINYINT(1) NULL,
  `admin` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`servicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_servico` DATETIME NULL,
  `servico_realizado` VARCHAR(3000) NULL,
  `valor_servico` DECIMAL(10,2) NULL,
  `valor_total` DECIMAL(10,2) NULL,
  `tipos_servico_id` INT NOT NULL,
  `clientes_id` INT NOT NULL,
  `profissionais_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipos_servico_id`, `clientes_id`, `profissionais_id`, `usuarios_id`),
  INDEX `fk_servicos_tipos_servico1_idx` (`tipos_servico_id` ASC),
  INDEX `fk_servicos_clientes1_idx` (`clientes_id` ASC),
  INDEX `fk_servicos_profissionais1_idx` (`profissionais_id` ASC),
  INDEX `fk_servicos_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_servicos_tipos_servico1`
    FOREIGN KEY (`tipos_servico_id`)
    REFERENCES `guara_tattoo`.`tipos_servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `guara_tattoo`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_profissionais1`
    FOREIGN KEY (`profissionais_id`)
    REFERENCES `guara_tattoo`.`profissionais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `guara_tattoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`materiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`materiais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  `marca` VARCHAR(100) NULL,
  `modelo` VARCHAR(100) NULL,
  `tipo` VARCHAR(100) NULL,
  `tamanho` VARCHAR(45) NULL,
  `preco_custo` DECIMAL(10,2) NULL,
  `margem_lucro` DOUBLE(10,2) NULL,
  `preco_venda` DECIMAL(10,2) NULL,
  `insumo` TINYINT(1) NULL,
  `venda` TINYINT(1) NULL,
  `estoque` DECIMAL(10,2) NULL,
  `pedCompra` DECIMAL(10,2) NULL,
  `foto` VARCHAR(3000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`servicos_materiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`servicos_materiais` (
  `servicos_id` INT NOT NULL,
  `materiais_id` INT NOT NULL,
  PRIMARY KEY (`servicos_id`, `materiais_id`),
  INDEX `fk_servicos_materiais_materiais1_idx` (`materiais_id` ASC),
  CONSTRAINT `fk_servicos_materiais_servicos1`
    FOREIGN KEY (`servicos_id`)
    REFERENCES `guara_tattoo`.`servicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_materiais_materiais1`
    FOREIGN KEY (`materiais_id`)
    REFERENCES `guara_tattoo`.`materiais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`tipos_movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`tipos_movimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  `entrada_valor` INT NULL,
  `entrada_material` INT NULL,
  `ativo` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`caixas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`caixas` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL,
  `nome_micro` VARCHAR(100) NULL,
  `notificar_usuario_fechamento` TINYINT(1) NULL,
  `hora_fechamento` VARCHAR(8) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`formas_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`formas_pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  `permitir_parcel` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`pagamentos_movimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`pagamentos_movimentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NULL,
  `desconto` DOUBLE(10,2) NULL,
  `formas_pagamento_id` INT NOT NULL,
  PRIMARY KEY (`id`, `formas_pagamento_id`),
  INDEX `fk_pagamentos_movimentos_formas_pagamento1_idx` (`formas_pagamento_id` ASC),
  CONSTRAINT `fk_pagamentos_movimentos_formas_pagamento1`
    FOREIGN KEY (`formas_pagamento_id`)
    REFERENCES `guara_tattoo`.`formas_pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`movimentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`movimentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_movimento` DATETIME NULL,
  `obs` VARCHAR(500) NULL,
  `tipos_movimento_id` INT NOT NULL,
  `caixas_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `clientes_id` INT NULL DEFAULT 0,
  `pagamentos_movimentos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipos_movimento_id`, `caixas_id`, `usuarios_id`, `clientes_id`, `pagamentos_movimentos_id`),
  INDEX `fk_movimentos_tipos_movimento1_idx` (`tipos_movimento_id` ASC),
  INDEX `fk_movimentos_caixas1_idx` (`caixas_id` ASC),
  INDEX `fk_movimentos_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_movimentos_pagamentos_movimentos1_idx` (`pagamentos_movimentos_id` ASC),
  CONSTRAINT `fk_movimentos_tipos_movimento1`
    FOREIGN KEY (`tipos_movimento_id`)
    REFERENCES `guara_tattoo`.`tipos_movimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentos_caixas1`
    FOREIGN KEY (`caixas_id`)
    REFERENCES `guara_tattoo`.`caixas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `guara_tattoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentos_pagamentos_movimentos1`
    FOREIGN KEY (`pagamentos_movimentos_id`)
    REFERENCES `guara_tattoo`.`pagamentos_movimentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`status_caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`status_caixa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `caixas_id` INT NULL,
  `data_abertura` DATETIME NULL,
  `data_fechamento` DATETIME NULL,
  PRIMARY KEY (`id`, `caixas_id`),
  INDEX `fk_status_caixa_caixas1_idx` (`caixas_id` ASC),
  CONSTRAINT `fk_status_caixa_caixas1`
    FOREIGN KEY (`caixas_id`)
    REFERENCES `guara_tattoo`.`caixas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`totais_caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`totais_caixa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `caixas_id` INT NOT NULL,
  `valor` DECIMAL(10,2) NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`id`, `caixas_id`),
  INDEX `fk_totais_caixa_caixas1_idx` (`caixas_id` ASC),
  CONSTRAINT `fk_totais_caixa_caixas1`
    FOREIGN KEY (`caixas_id`)
    REFERENCES `guara_tattoo`.`caixas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`itens_movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`itens_movimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `servico_material` INT NULL,
  `cod_servico_material` INT NULL,
  `QNTD` DOUBLE(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`movimentos_itens_movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`movimentos_itens_movimento` (
  `movimentos_id` INT NULL,
  `itens_movimento_id` INT NULL,
  PRIMARY KEY (`movimentos_id`, `itens_movimento_id`),
  INDEX `fk_movimentos_itens_movimento_itens_movimento1_idx` (`itens_movimento_id` ASC),
  CONSTRAINT `fk_movimentos_itens_movimento_movimentos1`
    FOREIGN KEY (`movimentos_id`)
    REFERENCES `guara_tattoo`.`movimentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentos_itens_movimento_itens_movimento1`
    FOREIGN KEY (`itens_movimento_id`)
    REFERENCES `guara_tattoo`.`itens_movimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`usuarios_tipos_movimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`usuarios_tipos_movimento` (
  `usuarios_id` INT NOT NULL,
  `tipos_movimento_id` INT NOT NULL,
  PRIMARY KEY (`usuarios_id`, `tipos_movimento_id`),
  INDEX `fk_usuarios_tipos_movimento_tipos_movimento1_idx` (`tipos_movimento_id` ASC),
  CONSTRAINT `fk_usuarios_tipos_movimento_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `guara_tattoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_tipos_movimento_tipos_movimento1`
    FOREIGN KEY (`tipos_movimento_id`)
    REFERENCES `guara_tattoo`.`tipos_movimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`contas_pagar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`contas_pagar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movimentos_id` INT NULL,
  `formas_pagamento_id` INT NOT NULL,
  `emitente` VARCHAR(100) NULL,
  `destinatario` VARCHAR(100) NULL,
  `descricao` VARCHAR(100) NULL,
  `valor` DECIMAL(10,2) NULL,
  `vencimento` DATETIME NULL,
  `juros` DOUBLE(10,2) NULL,
  `pago` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `movimentos_id`, `formas_pagamento_id`),
  INDEX `fk_contas_pagar_movimentos1_idx` (`movimentos_id` ASC),
  INDEX `fk_contas_pagar_formas_pagamento1_idx` (`formas_pagamento_id` ASC),
  CONSTRAINT `fk_contas_pagar_movimentos1`
    FOREIGN KEY (`movimentos_id`)
    REFERENCES `guara_tattoo`.`movimentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contas_pagar_formas_pagamento1`
    FOREIGN KEY (`formas_pagamento_id`)
    REFERENCES `guara_tattoo`.`formas_pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`operadoras_cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`operadoras_cartao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  `ativo` TINYINT(1) NULL,
  `credito_dias_pagamento` INT(5) NULL,
  `debito_horas_pagamento` INT(5) NULL,
  `taxa` DOUBLE(10,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`contas_receber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`contas_receber` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movimentos_id` INT NOT NULL,
  `formas_pagamento_id` INT NOT NULL,
  `emitente` VARCHAR(100) NULL,
  `destinatario` VARCHAR(100) NULL,
  `descricao` VARCHAR(100) NULL,
  `valor` DECIMAL(10,2) NULL,
  `vencimento` DATETIME NULL,
  `juros` DOUBLE(10,2) NULL,
  `pago` TINYINT(1) NULL,
  PRIMARY KEY (`id`, `movimentos_id`, `formas_pagamento_id`),
  INDEX `fk_contas_receber_movimentos1_idx` (`movimentos_id` ASC),
  INDEX `fk_contas_receber_formas_pagamento1_idx` (`formas_pagamento_id` ASC),
  CONSTRAINT `fk_contas_receber_movimentos1`
    FOREIGN KEY (`movimentos_id`)
    REFERENCES `guara_tattoo`.`movimentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contas_receber_formas_pagamento1`
    FOREIGN KEY (`formas_pagamento_id`)
    REFERENCES `guara_tattoo`.`formas_pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`config` (
  `id` INT NOT NULL,
  `emailLoja` VARCHAR(100) NULL,
  `senhaEmail` VARCHAR(100) NULL,
  `imagemLogo` VARCHAR(1000) NULL,
  `modeloEmailSessao` VARCHAR(1000) NULL,
  `modeloEmailAniv` VARCHAR(1000) NULL,
  `modeloEmailAgend` VARCHAR(1000) NULL,
  `host` VARCHAR(200) NULL,
  `porta` INT NULL,
  `diasRetorno_cliente` INT NULL,
  `tipos_servico_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guara_tattoo`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guara_tattoo`.`agenda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NULL,
  `clientes_id` INT NOT NULL,
  `profissionais_id` INT NOT NULL,
  `tipos_servico_id` INT NOT NULL,
  PRIMARY KEY (`id`, `clientes_id`, `profissionais_id`, `tipos_servico_id`),
  INDEX `fk_agenda_clientes1_idx` (`clientes_id` ASC),
  INDEX `fk_agenda_profissionais1_idx` (`profissionais_id` ASC),
  INDEX `fk_agenda_tipos_servico1_idx` (`tipos_servico_id` ASC),
  CONSTRAINT `fk_agenda_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `guara_tattoo`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_profissionais1`
    FOREIGN KEY (`profissionais_id`)
    REFERENCES `guara_tattoo`.`profissionais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agenda_tipos_servico1`
    FOREIGN KEY (`tipos_servico_id`)
    REFERENCES `guara_tattoo`.`tipos_servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
